<?xml version="1.0"?>
<package format="2">
  <name>pct_planner</name>
  <version>1.0.0</version>
  <description>Point Cloud Tomography based global planner for multi-layer environments.</description>

  <maintainer email="byangar@connect.ust.hk">Bowen Yang</maintainer>
  <license>GPL-2.0-only</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>actionlib</depend>
  <depend>actionlib_msgs</depend>
  <depend>geometry_msgs</depend>
  <build_depend>message_generation</build_depend>
  <exec_depend>message_runtime</exec_depend>
  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>

  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <export>
  </export>
</package>
